### ISSUE TITLE
`scoped-class` is not a helper error when developing an addon component consumed by a primary application

### ISSUE THREAD

**Issue by runspired** [soxhub/ember-scoped-css#218]
In luna-core I have added a new component that uses scoped-class. The consuming application when using this component throws an error that `scoped-class` is not a helper. luna-core build is running (via `pnpm start`)

I'm guessing there's some build magic that the consuming app does that isn't working correctly for this setup.

**Comment by NullVoxPopuli** [comment]
I think a good solve for this would be to add a runtime scoped-class that throws an error.

we already have a runtime definition for gjs/gts, but we can add a re-export for `scoped-class` for loose mode:
https://github.com/soxhub/ember-scoped-css/blob/main/ember-scoped-css/src/runtime/index.ts#L7
