### ISSUE TITLE
Will not compile css assets for gts files in app/components

### ISSUE THREAD

**Issue by runspired** [soxhub/ember-scoped-css#250]
given the CSS file `app/components/foo.css`

hbs and gjs files will compile appropriately. gts files will compile the component portion but not the css portion.

- `app/components/foo.gts` ❌
- `app/components/foo.gjs` ✅
- `app/components/foo.hbs` ✅

I tested this with both an embroider-strict and a classic-build app.

**Comment by NullVoxPopuli** [comment]
Without a reproduction (or what code you used), it'll be hard to know what problem you ran in to.

We have tests with gts, and they work.

**Comment by NullVoxPopuli** [comment]
Gonna close for now, we can re-open if there is a repro
